### ISSUE TITLE
How can I find the source code that contains vulnerabilities? 

### ISSUE THREAD

**Issue by majd-alhafi** [AUEB-BALab/VulinOSS#7]
Hello dear Antonis Gkortzis.

First I want to say thanks for this great repo.

But I still have a little thing that confused me. Does the database contain a table or column that refers to the source code that includes some vulnerabilities, rather than the URL of the project?

Have a nice day!

**Comment by AntonisGkortzis** [comment]
Dear Majd, 

Thank you for your interest in this repository!  

Using the project's URL and the vulnerable version, you can locally clone the repository and revert it to that version (by using the corresponding TAG or BRANCH). The database does not include a direct reference to the line of code where you can find the vulnerability since this detail is not always disclosed in the vulnerability report.

Did I answer your question?

Best,
Antonis
